# Generated by Django 5.2.11 on 2026-06-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='analytics_u_event_t_c59616_idx',
            old_name='analytics_u_event_t_6dc5b0_idx',
        ),
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='analytics_u_languag_0602ff_idx',
            old_name='analytics_u_languag_dfa80c_idx',
        ),
    ]
