# Generated by Django 4.2 on 2026-06-06 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CognateSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proto_form",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("gloss", models.CharField(blank=True, max_length=512)),
                ("notes", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(db_index=True, default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-confidence_score", "proto_form"],
            },
        ),
        migrations.CreateModel(
            name="CognateEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(db_index=True, max_length=16)),
                ("word", models.CharField(db_index=True, max_length=255)),
                ("lemma", models.CharField(blank=True, max_length=255)),
                ("ipa", models.CharField(blank=True, max_length=255)),
                ("meaning", models.CharField(blank=True, max_length=512)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("confidence_score", models.FloatField(db_index=True, default=0.0)),
                (
                    "cognate_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="cognates.cognateset",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="cognateentry",
            index=models.Index(
                fields=["language", "word"], name="cognates_co_languag_5435da_idx"
            ),
        ),
    ]
