import json
import os
import re

from django.core.management.base import BaseCommand


class Command(BaseCommand):
    help = "Validate backend/data/morphology/uzbek_rules.json and write report"

    def add_arguments(self, parser):
        parser.add_argument("--path", help="Path to morphology rules dir", default=None)

    def handle(self, *args, **options):
        base = options.get("path") or os.path.join("backend", "data", "morphology")
        src = os.path.join(base, "uzbek_rules.json")
        # Place reports alongside the morphology data directory under ../reports
        reports_dir = os.path.join(os.path.dirname(base), "reports")
        reports_dir = os.path.abspath(reports_dir)
        os.makedirs(reports_dir, exist_ok=True)
        report_path = os.path.join(reports_dir, "uzbek_morphology_report.json")

        if not os.path.isfile(src):
            self.stdout.write(self.style.ERROR(f"Missing file: {src}"))
            return

        with open(src, encoding="utf-8") as fh:
            data = json.load(fh)

        rules = data.get("rules", [])
        problems = []
        suffix_set = set()
        synthetic_count = 0
        impossible = []
        invalid_examples = []
        category_counts = {}

        for idx, r in enumerate(rules):
            suf = r.get("suffix")
            stype = r.get("suffix_type", "")
            # count categories
            category_counts[stype] = category_counts.get(stype, 0) + 1

            # detect synthetic marker
            if stype == "AutoGenerated":
                synthetic_count += 1

            # duplicates
            key = (suf, stype)
            if key in suffix_set:
                problems.append({"type": "duplicate", "index": idx, "suffix": suf, "suffix_type": stype})
            suffix_set.add(key)

            # impossible suffix detection: spaces, digits, or control chars
            if not suf or re.search(r"\s|\d|[^\w'-\u0080-\uffff]", suf):
                impossible.append({"index": idx, "suffix": suf})

            # examples validation: should be a list and contain plausible example strings
            ex = r.get("examples")
            if not isinstance(ex, list) or len(ex) == 0:
                invalid_examples.append({"index": idx, "suffix": suf, "examples": ex})

        report = {
            "total_rules": len(rules),
            "synthetic_rules": synthetic_count,
            "duplicates_found": len([p for p in problems if p.get("type") == "duplicate"]),
            "impossible_suffixes": impossible,
            "invalid_examples": invalid_examples,
            "category_counts": category_counts,
            "problems_sample": problems[:25],
        }

        with open(report_path, "w", encoding="utf-8") as out:
            json.dump(report, out, ensure_ascii=False, indent=2)

        self.stdout.write(self.style.SUCCESS(f"Wrote validation report to {report_path}"))
