# Generated by Django 4.2 on 2026-06-06 10:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('raw_text', models.TextField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorpusSentence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(db_index=True)),
                ('text', models.TextField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('normalized', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='corpus.corpusdocument')),
            ],
        ),
        migrations.CreateModel(
            name='CorpusSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorpusToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(db_index=True)),
                ('text', models.CharField(max_length=400)),
                ('norm', models.CharField(blank=True, max_length=400)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.corpussentence')),
            ],
        ),
        migrations.AddField(
            model_name='corpusdocument',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='corpus.corpussource'),
        ),
        migrations.AddIndex(
            model_name='corpustoken',
            index=models.Index(fields=['text'], name='corpus_corp_text_b5342c_idx'),
        ),
        migrations.AddIndex(
            model_name='corpussentence',
            index=models.Index(fields=['checksum'], name='corpus_corp_checksu_1d72bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='corpussentence',
            unique_together={('document', 'order')},
        ),
        migrations.AddIndex(
            model_name='corpusdocument',
            index=models.Index(fields=['language', 'checksum'], name='corpus_corp_languag_030edb_idx'),
        ),
    ]
