from django.test import TestCase
from django.test import Client
from django.core.management import call_command
from apps.morphology.services.morphology_service import analyze, batch_analyze
from apps.morphology.models import MorphologicalRule


class MorphologyServiceTests(TestCase):
    def setUp(self):
        # create a minimal set of Uzbek rules
        MorphologicalRule.objects.create(language="uz", suffix="lar", suffix_type="plural", confidence_score=1.0)
        MorphologicalRule.objects.create(language="uz", suffix="imiz", suffix_type="possessive", confidence_score=1.0)
        MorphologicalRule.objects.create(language="uz", suffix="dan", suffix_type="ablative", confidence_score=1.0)

    def test_analyze_complex_chain(self):
        analyses = analyze("kitoblarimizdan", "uz")
        self.assertTrue(len(analyses) >= 1)
        top = analyses[0]
        self.assertEqual(top["root"], "kitob")
        self.assertEqual([s["suffix"] for s in top["suffixes"]], ["lar", "imiz", "dan"])

    def test_batch_analyze(self):
        res = batch_analyze(["kitoblarimizdan", "kitoblar"], "uz")
        self.assertEqual(len(res), 2)
        self.assertEqual(res[0][0]["root"], "kitob")

    def test_seed_uzbek_rules_creates_500(self):
        # Use management command to seed morphology from data/morphology
        import os
        here = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        data_dir = os.path.join(here, "data", "morphology")
        call_command("seed_morphology", path=data_dir)
        count = MorphologicalRule.objects.filter(language="uz").count()
        # Updated target for curated expansion: at least 300 rules
        self.assertGreaterEqual(count, 300)

    def test_ambiguity_yazuvchi(self):
        # create ambiguity: 'yoz' + 'uvchi' and 'yozuvchi' as whole
        MorphologicalRule.objects.create(language="uz", suffix="uvchi", suffix_type="agentive", confidence_score=0.9)
        MorphologicalRule.objects.create(language="uz", suffix="chi", suffix_type="agentive2", confidence_score=0.7)
        MorphologicalRule.objects.create(language="uz", suffix="yozuvchi", suffix_type="lexical", confidence_score=0.8)
        analyses = analyze("yozuvchi", "uz", max_results=5)
        # Expect at least two analyses (split vs lexical)
        self.assertTrue(len(analyses) >= 2)

    def test_validate_command_writes_report(self):
        import os
        here = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        data_dir = os.path.join(here, "data", "morphology")
        # run validator
        call_command("validate_uzbek_morphology", path=data_dir)
        report_path = os.path.join(here, "data", "reports", "uzbek_morphology_report.json")
        self.assertTrue(os.path.isfile(report_path))
        with open(report_path, encoding="utf-8") as fh:
            import json

            rep = json.load(fh)
        self.assertIn("total_rules", rep)
        self.assertIn("category_counts", rep)

    def test_analyzer_prefers_curated(self):
        # curated high-confidence rule vs auto-generated low confidence
        MorphologicalRule.objects.create(language="uz", suffix="uvchi", suffix_type="agentive", confidence_score=0.95)
        MorphologicalRule.objects.create(language="uz", suffix="autogen1", suffix_type="AutoGenerated", confidence_score=0.9)
        # analyze a surface that can be split two ways: 'yozuvchi' or 'yoz'+'uvchi'
        MorphologicalRule.objects.create(language="uz", suffix="yoz", suffix_type="stem", confidence_score=1.0)
        analyses = analyze("yozuvchi", "uz", max_results=3)
        # multi-analysis mode should include a derivational 'uvchi' analysis
        suffix_chains = []
        for analysis in analyses:
            suffix_chains.append([
                s.get("suffix") if isinstance(s, dict) else s
                for s in analysis.get("suffixes", [])
            ])
        self.assertTrue(any("uvchi" in chain for chain in suffix_chains))

    def test_turkish_complex_chain(self):
        analyses = analyze("kitaplarımızdan", "tr", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertIn(("kitap", ["lar", "ımız", "dan"]), chains)

    def test_turkish_major_vowel_harmony_blocks_invalid_plural(self):
        analyses = analyze("evlar", "tr", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertNotIn(("ev", ["lar"]), chains)

    def test_azerbaijani_complex_chain(self):
        analyses = analyze("kitablarımızdan", "az", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertIn(("kitab", ["lar", "ımız", "dan"]), chains)

    def test_azerbaijani_major_vowel_harmony_blocks_invalid_plural(self):
        analyses = analyze("evlar", "az", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertNotIn(("ev", ["lar"]), chains)

    def test_kazakh_complex_chain(self):
        kitap = "\u043a\u0456\u0442\u0430\u043f"
        tar = "\u0442\u0430\u0440"
        ymyz = "\u044b\u043c\u044b\u0437"
        dan = "\u0434\u0430\u043d"
        analyses = analyze(kitap + tar + ymyz + dan, "kk", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertIn((kitap, [tar, ymyz, dan]), chains)

    def test_kazakh_major_vowel_harmony_blocks_invalid_plural(self):
        uy = "\u04af\u0439"
        lar = "\u043b\u0430\u0440"
        analyses = analyze(uy + lar, "kk", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertNotIn((uy, [lar]), chains)

    def test_kyrgyz_complex_chain(self):
        kitep = "\u043a\u0438\u0442\u0435\u043f"
        ter = "\u0442\u0435\u0440"
        ibiz = "\u0438\u0431\u0438\u0437"
        den = "\u0434\u0435\u043d"
        analyses = analyze(kitep + ter + ibiz + den, "ky", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertIn((kitep, [ter, ibiz, den]), chains)

    def test_kyrgyz_major_vowel_harmony_blocks_invalid_plural(self):
        uy = "\u04af\u0439"
        lar = "\u043b\u0430\u0440"
        analyses = analyze(uy + lar, "ky", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertNotIn((uy, [lar]), chains)

    def test_turkmen_complex_chain(self):
        analyses = analyze("kitaplarymyzdan", "tk", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertIn(("kitap", ["lar", "ymyz", "dan"]), chains)

    def test_turkmen_major_vowel_harmony_blocks_invalid_plural(self):
        oy = "\u00f6\u00fd"
        analyses = analyze(oy + "lar", "tk", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertNotIn((oy, ["lar"]), chains)

    def test_uyghur_complex_chain(self):
        kitab = "\u0643\u0649\u062a\u0627\u0628"
        lar = "\u0644\u0627\u0631"
        imiz = "\u0649\u0645\u0649\u0632"
        din = "\u062f\u0649\u0646"
        analyses = analyze(kitab + lar + imiz + din, "ug", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertIn((kitab, [lar, imiz, din]), chains)

    def test_uyghur_front_plural(self):
        adem = "\u0626\u0627\u062f\u06d5\u0645"
        ler = "\u0644\u06d5\u0631"
        analyses = analyze(adem + ler, "ug", max_results=10)
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertIn((adem, [ler]), chains)

    def test_old_turkic_teŋri_transliteration_and_split(self):
        teng = "\U00010c45\U00010c2d"
        ri = "\U00010c3c\U00010c03"
        analyses = analyze(teng + ri, "otk", max_results=10)
        self.assertTrue(any(a.get("lemma") == "te\u014bri" for a in analyses))
        chains = [
            (
                analysis.get("root"),
                [
                    s.get("suffix") if isinstance(s, dict) else s
                    for s in analysis.get("suffixes", [])
                ],
            )
            for analysis in analyses
        ]
        self.assertIn((teng, [ri]), chains)

    def test_old_turkic_latin_lookup(self):
        analyses = analyze("te\u014bri", "otk", max_results=5)
        self.assertTrue(any(a.get("lemma") == "te\u014bri" for a in analyses))

    def test_analyze_endpoint_is_public_for_web_ui(self):
        client = Client(HTTP_HOST="localhost")
        response = client.get("/api/morphology/analyze/", {"word": "kitoblarimizdan", "language": "uz"})
        self.assertEqual(response.status_code, 200)
        self.assertIn("analyses", response.json())

    def test_universal_analyze_endpoint_is_public_for_web_ui(self):
        client = Client(HTTP_HOST="localhost")
        response = client.get("/api/morphology/universal-analyze/", {"word": "kitoblarimizdan", "language": "uz"})
        self.assertEqual(response.status_code, 200)
        self.assertIn("analysis", response.json())
