# Generated by Django 4.2 on 2026-06-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proto_form", models.CharField(blank=True, max_length=200, null=True)),
                ("old_turkic_form", models.TextField(blank=True, null=True)),
                (
                    "middle_turkic_form",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("modern_language", models.CharField(max_length=16)),
                ("modern_form", models.CharField(max_length=200)),
                ("ipa", models.CharField(blank=True, max_length=200, null=True)),
                ("gloss", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("confidence_score", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("SOUND_CHANGE", "Sound change"),
                            ("MORPHOLOGICAL_CHANGE", "Morphological change"),
                            ("SEMANTIC_CHANGE", "Semantic change"),
                            ("ORTHOGRAPHIC_CHANGE", "Orthographic change"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("confidence_score", models.FloatField(default=1.0)),
                (
                    "child_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="historical.historicalform",
                    ),
                ),
                (
                    "parent_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="historical.historicalform",
                    ),
                ),
            ],
        ),
    ]
